# Standard .travis.yml for a Mautic plugin. Adjust env variables as needed.
env:
  global:
    # The exact plugin folder/bundle name.
    - "MAUTIC_PLUGIN=MauticExtendedFieldBundle"

dist: precise

language: php

services:
  - mysql

php:
  # Only test on PHP 7.3
  - 7.3

before_install:
  # Create mautictest database
  - mysql -e 'DROP DATABASE IF EXISTS mautictest;'
  - mysql -e 'CREATE DATABASE mautictest;'
  - mysql -u root -e 'CREATE USER IF NOT EXISTS travis@localhost; GRANT ALL ON *.* TO travis@localhost;'
  
  # Rollback to Composer 1
  - composer self-update --1

  # Turn off XDebug.
  - phpenv config-rm xdebug.ini || return

  # Install dependencies in parallel.
  - travis_retry composer global require hirak/prestissimo

  # Set to test environment for Symfony's commands in post install commands.
  - export SYMFONY_ENV="test"

  # Install PHPSTAN for PHP 7+
  - composer global require phpstan/phpstan-shim:0.8.5

  # Get latest 3.x mautic
  - git clone -b 3.3 https://github.com/mautic/mautic.git /tmp/mautic
  - cd /tmp/mautic
  - cp .env.dist .env
  - git checkout 3.3
  - cd -

  # Combine core with our plugin.
  - mkdir -p /tmp/mautic/plugins/$MAUTIC_PLUGIN
  - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ /tmp/mautic/plugins/$MAUTIC_PLUGIN
  - rsync -r --delete-after --quiet /tmp/mautic/ $TRAVIS_BUILD_DIR/

install:
  - composer install --no-suggest
        
script:
  # Run PHPUnit including core tests to find potential BC breaks.
  - composer test

  # Run PHPSTAN analysis for PHP 7+ only in the scope of this plugin.
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then ~/.composer/vendor/phpstan/phpstan-shim/phpstan.phar analyse plugins/$MAUTIC_PLUGIN; fi

  # Check code standards for PHP 7.3 only in the scope of this plugin.
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then bin/php-cs-fixer fix -v --dry-run --diff plugins/$MAUTIC_PLUGIN; fi

jobs:
  include:
    - stage: test
      php: 7.3
      env: DB=mariadb
      addons:
        mariadb: '10.2'
